import { describe, expect, it } from "vitest";
import {
  extractComments,
  lintProse,
  splitSentences,
  stripMarkdown,
  wordCount,
  // @ts-expect-error — .mjs script, no type declarations
} from "../../.github/scripts/check-plain-language.mjs";

const rules = (findings: { rule: string }[]) => findings.map((f) => f.rule);

describe("stripMarkdown", () => {
  it("collapses inline code, links, and URLs to single tokens", () => {
    const out = stripMarkdown(
      "Run `pnpm lint:dietary --with --many --flags` then see [docs](https://x.dev/a/b)."
    );
    expect(out).toContain("CODE");
    expect(out).not.toContain("pnpm");
    expect(out).toContain("docs");
    expect(out).not.toContain("https://");
  });

  it("strips list bullets and emphasis markers", () => {
    expect(stripMarkdown("- **bold** point")).toBe("bold point");
    expect(stripMarkdown("2. numbered item")).toBe("numbered item");
  });
});

describe("splitSentences / wordCount", () => {
  it("splits on terminal punctuation", () => {
    expect(splitSentences("One is here. Two is here! Three?")).toHaveLength(3);
  });

  it("does not split after common abbreviations", () => {
    expect(splitSentences("Use safe items, e.g. rice and corn.")).toHaveLength(1);
  });

  it("treats a fragment without terminal punctuation as one sentence", () => {
    expect(splitSentences("a long bullet fragment with no period")).toHaveLength(1);
  });

  it("counts words", () => {
    expect(wordCount("three little words")).toBe(3);
  });
});

describe("lintProse — R1 sentence-length", () => {
  const longSentence =
    "This sentence definitely keeps on going with far too many words for the limit because it lists one two three four five six seven extra clauses.";

  it("flags sentences over 25 words", () => {
    expect(rules(lintProse(longSentence))).toContain("R1 sentence-length");
  });

  it("passes a 25-word-or-shorter sentence", () => {
    expect(lintProse("This sentence is short and clear.")).toHaveLength(0);
  });

  it("counts an inline code span as one word", () => {
    const s =
      "Run `a very long command with nine words inside the span okay` and then check the output file, the log file, and the summary now.";
    expect(rules(lintProse(s))).not.toContain("R1 sentence-length");
  });
});

describe("lintProse — R2 paragraph-length", () => {
  const sevenSentences = Array.from({ length: 7 }, (_, i) => `Sentence number ${i} is here.`).join(
    " "
  );

  it("flags paragraphs over 6 sentences", () => {
    expect(rules(lintProse(sevenSentences))).toContain("R2 paragraph-length");
  });

  it("can be disabled for short-form scopes like the TL;DR", () => {
    expect(rules(lintProse(sevenSentences, { paragraphRule: false }))).not.toContain(
      "R2 paragraph-length"
    );
  });

  it("resets paragraphs on blank lines", () => {
    const twoParas = `${sevenSentences.split(" is here. ").slice(0, 4).join(" is here. ")} is here.\n\nShort second paragraph.`;
    expect(rules(lintProse(twoParas))).not.toContain("R2 paragraph-length");
  });
});

describe("lintProse — R3 active-voice heuristic", () => {
  it("flags a passive construction", () => {
    expect(rules(lintProse("The plan was generated by the workflow."))).toContain(
      "R3 active-voice"
    );
  });

  it("does not flag active voice", () => {
    expect(rules(lintProse("The workflow generates the plan."))).not.toContain("R3 active-voice");
  });

  it("skips adjective-like exceptions", () => {
    expect(rules(lintProse("The team is excited about the launch."))).not.toContain(
      "R3 active-voice"
    );
  });
});

describe("lintProse — R4 simpler-word", () => {
  it("flags complex words and suggests the simple form", () => {
    type Finding = { rule: string; message: string };
    const findings: Finding[] = lintProse("We utilize the tool in order to facilitate review.");
    const r4 = findings.filter((f) => f.rule === "R4 simpler-word");
    expect(r4.length).toBeGreaterThanOrEqual(3);
    expect(r4.some((f) => f.message.includes('"use"'))).toBe(true);
    expect(r4.some((f) => f.message.includes('"to"'))).toBe(true);
    expect(r4.some((f) => f.message.includes('"help"'))).toBe(true);
  });

  it("matches whole words only", () => {
    expect(rules(lintProse("The initiated flow works."))).not.toContain("R4 simpler-word");
  });
});

describe("lintProse — markdown structure handling", () => {
  it("skips fenced code blocks entirely", () => {
    const md = [
      "```",
      "this fenced pseudo prose would be flagged were it prose because it runs on and on and on and on and on and on and on and on",
      "```",
    ].join("\n");
    expect(lintProse(md)).toHaveLength(0);
  });

  it("skips headings and tables", () => {
    const md = [
      "## A very long heading that is not a sentence and must never be counted as one even though it is long",
      "| a | very | long | table | row | with | many | cells | that | is | not | prose | at | all | in | any | way | shape | or | form | ok | yes | sure | fine | done |",
    ].join("\n");
    expect(lintProse(md)).toHaveLength(0);
  });

  it("reports line numbers for findings", () => {
    const md = ["Short first line.", "", "The plan was generated by the workflow."].join("\n");
    const findings: { rule: string; line: number }[] = lintProse(md);
    const f = findings.find((x) => x.rule === "R3 active-voice");
    expect(f?.line).toBe(3);
  });
});

describe("extractComments", () => {
  it("extracts line comments and block comments with line numbers", () => {
    const src = [
      "const a = 1; // trailing note here",
      "/*",
      " * a block comment body",
      " * across two lines",
      " */",
      "// standalone line",
    ].join("\n");
    const comments = extractComments(src);
    expect(comments).toHaveLength(3);
    expect(comments[0]).toMatchObject({ text: "trailing note here", line: 1 });
    expect(comments[1].text).toContain("a block comment body across two lines");
    expect(comments[2]).toMatchObject({ text: "standalone line", line: 6 });
  });

  it("returns nothing for comment-free source", () => {
    expect(extractComments("const x = 1;\nexport default x;")).toHaveLength(0);
  });
});
